---
- name: Update apt cache
  apt: update-cache=yes

- name: Ensure common packages are installed
  apt: name={{ item }} state=latest update_cache=false
  sudo: true
  with_items:
    - software-properties-common
    - python-software-properties
    - build-essential
    - libssl-dev
    - libexpat1-dev
    - git
    - curl
    - tcl
    - vim
    - htop
    - unzip