---
haproxy_global:
  chroot: /var/lib/haproxy
  log:
    - bind: 127.0.0.1
      facility: local0
      level: info
  description: "HAProxy Daemon"
  maxconn: 32768
  user: haproxy
  group: haproxy
  daemon: true

haproxy_default:
  log:
    - bind: 127.0.0.1
      facility: local1
      level: info
  mode: http
  retries: 3
  options:
   - httplog
   - dontlognull
   - http-server-close
   - forwardfor except 127.0.0.0/8
   - redispatch
  timeout:
   - http-request 5s
   - queue 1m
   - connect 5s
   - client 1m
   - server 1m
   - http-keep-alive 10s
   - tunnel 1h
   - check 5s

haproxy_frontends:
 - name: loadbalancer
   bind: '*:5555'
   mode: http
   default_backend: webservers

haproxy_backends:
 - name: webservers
   balance: roundrobin
   mode: http
   cookie: _backend insert indirect nocache
   servers:
    - name: backend1
      ip: 127.0.0.1
      port: 5000
      params:
        - maxconn 10000
        - weight 10
        - cookie ws1 check

    - name: backend2
      ip: 127.0.0.1
      port: 5001
      params:
        - maxconn 10000
        - weight 10
        - cookie ws2 check

haproxy_admin:
  bind: '*:57075'
  stats:
   - status: enable
   - hideversion: enable
   - uri: /
   - refresh: 10
   - auth: 'admin:hyLDT8Gd'

#
# Those default options are based on the following config file (/etc/haproxy/haproxy.cfg)
#
#
#global
#	log 127.0.0.1   local0
#	log 127.0.0.1   local1 notice
#	chroot /var/lib/haproxy
#	maxconn         4096
#	user            haproxy
#	group           haproxy
#	daemon
#
#defaults
#	log				global
#	mode            http
#	option                  httplog
#	option                  dontlognull
#	option http-server-close
#	option forwardfor       except 127.0.0.0/8
#	option                  redispatch
#	retries                 3
#	timeout http-request    10s
#	timeout queue           1m
#	timeout connect         10s
#	timeout client          1m
#	timeout server          1m
#	timeout http-keep-alive 10s
#	timeout check           10s
#	maxconn                 3000
#	errorfile 400 /etc/haproxy/errors/400.http
#	errorfile 403 /etc/haproxy/errors/403.http
#	errorfile 408 /etc/haproxy/errors/408.http
#	errorfile 500 /etc/haproxy/errors/500.http
#	errorfile 502 /etc/haproxy/errors/502.http
#	errorfile 503 /etc/haproxy/errors/503.http
#	errorfile 504 /etc/haproxy/errors/504.http
